name: Backend Deployment
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{secrets.IMAGE_NAME}}:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{secrets.IMAGE_NAME}}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.10.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Pull and deploy on server
        uses: appleboy/ssh-action@v0.5.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            docker compose pull backend
            docker compose down
            docker compose up -d
